# Generated by Django 5.0.6 on 2024-06-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="picture",
            field=models.URLField(max_length=500),
        ),
    ]
